//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyBLE_MTK_Application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath1 {
            get {
                return ((string)(this["RecentPath1"]));
            }
            set {
                this["RecentPath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath2 {
            get {
                return ((string)(this["RecentPath2"]));
            }
            set {
                this["RecentPath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath3 {
            get {
                return ((string)(this["RecentPath3"]));
            }
            set {
                this["RecentPath3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath4 {
            get {
                return ((string)(this["RecentPath4"]));
            }
            set {
                this["RecentPath4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string RecentPath5 {
            get {
                return ((string)(this["RecentPath5"]));
            }
            set {
                this["RecentPath5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal NumDUTs {
            get {
                return ((decimal)(this["NumDUTs"]));
            }
            set {
                this["NumDUTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Relevant")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationLogPath {
            get {
                return ((string)(this["ApplicationLogPath"]));
            }
            set {
                this["ApplicationLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveAppLogs {
            get {
                return ((bool)(this["AutoSaveAppLogs"]));
            }
            set {
                this["AutoSaveAppLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TestLogPath {
            get {
                return ((string)(this["TestLogPath"]));
            }
            set {
                this["TestLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLogTests {
            get {
                return ((bool)(this["AutoLogTests"]));
            }
            set {
                this["AutoLogTests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUT")]
        public string AutoLogTestsSetting {
            get {
                return ((string)(this["AutoLogTestsSetting"]));
            }
            set {
                this["AutoLogTestsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTestProgDialogMsg {
            get {
                return ((bool)(this["EnableTestProgDialogMsg"]));
            }
            set {
                this["EnableTestProgDialogMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MultiDUTEnable {
            get {
                return ((bool)(this["MultiDUTEnable"]));
            }
            set {
                this["MultiDUTEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UART")]
        public string ConnectionType {
            get {
                return ((string)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PauseTestsOnFailure {
            get {
                return ((bool)(this["PauseTestsOnFailure"]));
            }
            set {
                this["PauseTestsOnFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseSerialDialog {
            get {
                return ((bool)(this["CloseSerialDialog"]));
            }
            set {
                this["CloseSerialDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAUseProgrammer {
            get {
                return ((bool)(this["BDAUseProgrammer"]));
            }
            set {
                this["BDAUseProgrammer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAIncrement {
            get {
                return ((bool)(this["BDAIncrement"]));
            }
            set {
                this["BDAIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000000000")]
        public string BDA {
            get {
                return ((string)(this["BDA"]));
            }
            set {
                this["BDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort0 {
            get {
                return ((string)(this["DUTSerialPort0"]));
            }
            set {
                this["DUTSerialPort0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort1 {
            get {
                return ((string)(this["DUTSerialPort1"]));
            }
            set {
                this["DUTSerialPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort2 {
            get {
                return ((string)(this["DUTSerialPort2"]));
            }
            set {
                this["DUTSerialPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort3 {
            get {
                return ((string)(this["DUTSerialPort3"]));
            }
            set {
                this["DUTSerialPort3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort4 {
            get {
                return ((string)(this["DUTSerialPort4"]));
            }
            set {
                this["DUTSerialPort4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort5 {
            get {
                return ((string)(this["DUTSerialPort5"]));
            }
            set {
                this["DUTSerialPort5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort6 {
            get {
                return ((string)(this["DUTSerialPort6"]));
            }
            set {
                this["DUTSerialPort6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort7 {
            get {
                return ((string)(this["DUTSerialPort7"]));
            }
            set {
                this["DUTSerialPort7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort8 {
            get {
                return ((string)(this["DUTSerialPort8"]));
            }
            set {
                this["DUTSerialPort8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort9 {
            get {
                return ((string)(this["DUTSerialPort9"]));
            }
            set {
                this["DUTSerialPort9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort10 {
            get {
                return ((string)(this["DUTSerialPort10"]));
            }
            set {
                this["DUTSerialPort10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort11 {
            get {
                return ((string)(this["DUTSerialPort11"]));
            }
            set {
                this["DUTSerialPort11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort12 {
            get {
                return ((string)(this["DUTSerialPort12"]));
            }
            set {
                this["DUTSerialPort12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort13 {
            get {
                return ((string)(this["DUTSerialPort13"]));
            }
            set {
                this["DUTSerialPort13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort14 {
            get {
                return ((string)(this["DUTSerialPort14"]));
            }
            set {
                this["DUTSerialPort14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTSerialPort15 {
            get {
                return ((string)(this["DUTSerialPort15"]));
            }
            set {
                this["DUTSerialPort15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreDUTs {
            get {
                return ((bool)(this["IgnoreDUTs"]));
            }
            set {
                this["IgnoreDUTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MTKSerialPort {
            get {
                return ((string)(this["MTKSerialPort"]));
            }
            set {
                this["MTKSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnritsuSerialPort {
            get {
                return ((string)(this["AnritsuSerialPort"]));
            }
            set {
                this["AnritsuSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DUTMultiplexerSerialPort {
            get {
                return ((string)(this["DUTMultiplexerSerialPort"]));
            }
            set {
                this["DUTMultiplexerSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
  <string>Configure...</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerName"]));
            }
            set {
                this["DUTProgrammerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerVoltage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerVoltage"]));
            }
            set {
                this["DUTProgrammerVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerPM {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerPM"]));
            }
            set {
                this["DUTProgrammerPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerConn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerConn"]));
            }
            set {
                this["DUTProgrammerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerClock {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerClock"]));
            }
            set {
                this["DUTProgrammerClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerPA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerPA"]));
            }
            set {
                this["DUTProgrammerPA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerVerify {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerVerify"]));
            }
            set {
                this["DUTProgrammerVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DUTProgrammerHexPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DUTProgrammerHexPath"]));
            }
            set {
                this["DUTProgrammerHexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AnritsuScriptID {
            get {
                return ((int)(this["AnritsuScriptID"]));
            }
            set {
                this["AnritsuScriptID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AnritsuOutputPower {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnritsuOutputPower"]));
            }
            set {
                this["AnritsuOutputPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
  <string>0.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AnritsuTXPower {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnritsuTXPower"]));
            }
            set {
                this["AnritsuTXPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int AnritsuNumPKTS {
            get {
                return ((int)(this["AnritsuNumPKTS"]));
            }
            set {
                this["AnritsuNumPKTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configure...")]
        public string BDAProgrammerName {
            get {
                return ((string)(this["BDAProgrammerName"]));
            }
            set {
                this["BDAProgrammerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerVoltage {
            get {
                return ((string)(this["BDAProgrammerVoltage"]));
            }
            set {
                this["BDAProgrammerVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerPM {
            get {
                return ((string)(this["BDAProgrammerPM"]));
            }
            set {
                this["BDAProgrammerPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerConn {
            get {
                return ((string)(this["BDAProgrammerConn"]));
            }
            set {
                this["BDAProgrammerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerClock {
            get {
                return ((string)(this["BDAProgrammerClock"]));
            }
            set {
                this["BDAProgrammerClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerPA {
            get {
                return ((string)(this["BDAProgrammerPA"]));
            }
            set {
                this["BDAProgrammerPA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerVerify {
            get {
                return ((string)(this["BDAProgrammerVerify"]));
            }
            set {
                this["BDAProgrammerVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDAProgrammerHexPath {
            get {
                return ((string)(this["BDAProgrammerHexPath"]));
            }
            set {
                this["BDAProgrammerHexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BDAProgrammerGlobal {
            get {
                return ((bool)(this["BDAProgrammerGlobal"]));
            }
            set {
                this["BDAProgrammerGlobal"] = value;
            }
        }
    }
}
